# A workflow that tests this action

name: CI test workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run the CI tests

    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@8e0b4153524c217e5dce81df0986478e95a7004a
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            deb.debian.org:80
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443
            security.debian.org:80

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - name: Run test scripts
        working-directory: ${{ github.workspace }}
        id: test
        shell: bash
        run: |
          chmod +x "test/test.sh"
          rm -f "test/test-*.txt"
          bash test/test.sh > test/test-result.txt
          echo "test-result=$(grep "Test result:" ${{ github.workspace }}/test/test-result.txt)" >>"$GITHUB_OUTPUT"
        continue-on-error: true

      - name: Read test details  file.
        id: details
        uses: juliangruber/read-file-action@19f30157c58fc24c866eaac38e31de968fb16929
        with:
          path: ${{ github.workspace }}/test/test-outputs.txt

      - name: Update test script comment on PR under test
        if: github.event_name == 'pull_request' && ( ${{ success() }} || ${{ failure() }} )
        uses: thollander/actions-comment-pull-request@ebf3fccffd3d30bb8b65e632e6433e710bfe1259
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Testing script results from test/test.sh
            ${{ steps.test.outputs.test-result }}

            <details><summary>Test script outputs from test/test.sh</summary>
            <p>

            ${{ steps.details.outputs.content }}

            </p>
            </details>
