# A workflow that tests this action

name: CI test workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run the CI tests

    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@aa817ef3512b39bbe179e1c24cc63b4a421ab219
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            deb.debian.org:80
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443
            security.debian.org:80

      - name: Checkout
        uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5

      - name: Run test scripts
        working-directory: ${{ github.workspace }}
        id: test
        shell: bash
        run: |
          chmod +x "test/test.sh"
          rm -f "test/test-*.txt"
          bash test/test.sh > test/test-result.txt
          echo "test-result=$(grep "Test result:" ${{ github.workspace }}/test/test-result.txt)" >>"$GITHUB_OUTPUT"
        continue-on-error: true

      - name: Read test details  file.
        id: details
        uses: juliangruber/read-file-action@cc341ded5e6547edbdf30bf7b4138a940433641b
        with:
          path: ${{ github.workspace }}/test/test-outputs.txt

      - name: Update test script comment on PR under test
        if: github.event_name == 'pull_request' && ( ${{ success() }} || ${{ failure() }} )
        uses: thollander/actions-comment-pull-request@8c77f42bbcc27c832a3a5962c8f9a60e34b594f3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Testing script results from test/test.sh
            ${{ steps.test.outputs.test-result }}

            <details><summary>Test script outputs from test/test.sh</summary>
            <p>

            ${{ steps.details.outputs.content }}

            </p>
            </details>
